import { chromium } from '../../../maqueta3d/node_modules/playwright-core/index.mjs';
const browser=await chromium.launch({headless:true,args:['--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});
const page=await browser.newPage({viewport:{width:1440,height:1040},deviceScaleFactor:1.5});
page.setDefaultTimeout(20000);
await page.goto('http://127.0.0.1:5173');
await page.getByLabel('Inventario',{exact:true}).selectOption('publicSpaces');
await page.locator('.territory-map').waitFor();
await page.locator('.map-wrap').screenshot({path:'entregables/presentacion-ampliada/assets/mapa.png'});
await page.getByLabel('Buscar espacio o barrio').fill('epou-9465');
await page.locator('.record').first().click();
await page.locator('.detail').screenshot({path:'entregables/presentacion-ampliada/assets/ficha.png'});
await page.getByRole('button',{name:'Preparar este espacio',exact:true}).click();
const panel=page.locator('.acopio-capacity');
await panel.waitFor();
for(const [label,value] of [['Área no utilizable (m²)','100'],['Circulación, accesos y evacuación (m²)','80'],['Atención, entrega y espera (m²)','60'],['Otros usos y ocupación existente (m²)','40'],['Huella por módulo de almacenamiento (m²)','10'],['Módulos de almacenamiento propuestos','20']]) await page.getByLabel(label,{exact:true}).fill(value,{force:true});
await panel.locator('[role=status]').screenshot({path:'entregables/presentacion-ampliada/assets/exceso.png'});
await page.getByLabel('Módulos de almacenamiento propuestos',{exact:true}).fill('16',{force:true});
await panel.locator('[role=status]').screenshot({path:'entregables/presentacion-ampliada/assets/ajuste.png'});
await page.getByText('Preparar aviso SMS de acopio',{exact:true}).click();
await page.getByLabel('Destinatarios simulados').fill('100');
await page.getByRole('button',{name:'Simular envío masivo',exact:true}).click();
await page.locator('.sms-results').waitFor();
await page.locator('.sms-results').screenshot({path:'entregables/presentacion-ampliada/assets/sms.png'});
await page.getByRole('button',{name:'04 Análisis preventivo'}).click();
await page.locator('.prevention-grid').first().screenshot({path:'entregables/presentacion-ampliada/assets/prevencion.png'});
await browser.close();
